development:
  user: fedoraAdmin
  password: <%= ENV['DEV_ADMIN_PASSWORD'] %>
  url: <%= ENV['DEV_FEDORA'] %>
  base_path: /dev
test:
  user: fedoraAdmin
  password: <%= ENV['TEST_ADMIN_PASSWORD'] %>
  url: <%= ENV['TEST_FEDORA'] %>
  base_path: /test
production:
  user: fedoraAdmin
  password: <%= ENV['PROD_ADMIN_PASSWORD'] %>
  url: <%= ENV['PRODUCTION_FEDORA'] %>
  base_path: /production
