development:
  user: fedoraAdmin
  password: <%= ENV['DEVELOPMENT_ADMIN_PASSWORD'] %>
  url: <%= ENV['DEVELOPMENT_FEDORA_URL'] %>
  base_path: <%= ENV['DEVELOPMENT_FEDORA_BASE_PATH'] %>
test:
  user: fedoraAdmin
  password: <%= ENV['TEST_ADMIN_PASSWORD'] %>
  url: <%= ENV['TEST_FEDORA'] %>
  base_path: <%= ENV['TEST_FEDORA_BASE_PATH'] %>
production:
  user: fedoraAdmin
  password: <%= ENV['PRODUCTION_ADMIN_PASSWORD'] %>
  url: <%= ENV['PRODUCTION_FEDORA_URL'] %>
  base_path: <%= ENV['PRODUCTION_FEDORA_BASE_PATH'] %>
